Feature/welcome view
JuanZea/capilog-frontend pull request #2
Opened 2022-01-22 21:42 UTC by Royk8

# Welcome Pago Up!
![unknown](https://user-images.githubusercontent.com/53505105/150656386-1f39991a-4dae-428f-a997-4025a5df2cbc.png)

2022-01-22 21:44 UTC, JuanZea requested changes

2022-01-22 21:44 UTC, JuanZea commented on src/App.vue
> +			<button class="button btn-primary">Login</button>
Los botones deberías estar en español

2022-01-23 01:23 UTC, JuanZea approved these changes

2022-01-24 22:46 UTC, JhonierCordoba approved these changes

2022-01-24 22:46 UTC, merged